##############################
# Test file
##############################
version: '2.1'
services:
  node:
    image: node

  redis:
    image: redis

  nginx:
    image: nginx
    depends_on:
      - redis

  hello-world:
    image: hello-world
    volumes_from:
      - node
    depends_on:
      nginx:
        condition: service_healthy
